/**/controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_group_position_controller_gimbals:
      type: position_controllers/JointGroupPositionController
    joint_group_position_controller_joints:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    attitude_controller:
      type: flight_controllers/SimulationAttitudeController

/**/attitude_controller:
  ros__parameters:
    imu: spinal_imu
    mag: spinal_mag
    rotor_joints:
      - rotor1
      - rotor2
      - rotor3
      - rotor4

/**/mujoco_attitude_controller:
  ros__parameters:
    update_rate: 1000.0
    use_ground_truth: true
    rotor_joints:
      - rotor1
      - rotor2
      - rotor3
      - rotor4

/**/mujoco_bridge:
  ros__parameters:
    step_rate: 1000.0
    render_rate: 60.0
    fc_site_name: fc
    main_body_name: base_link
    rotor_joints:
      - rotor1
      - rotor2
      - rotor3
      - rotor4
    # initial_rotor_forces: [4.06, 4.06, 4.06, 4.06]
    initial_hold_release_threshold: 0.1
    hold_initial_pose: false
    max_rotor_force: 20.0
    use_urdf_rotor_torque_rate: true
    kinematic_joint_control: false
    kinematic_joint_velocity_limit: 3.0
    reverse_joint_targets: []

    ground_truth_pub_rate: 0.01
    ground_truth_pos_noise: 0.001
    ground_truth_vel_noise: 0.005
    ground_truth_rot_noise: 0.001
    ground_truth_angular_noise: 0.005

    mocap_pub_rate: 0.01
    mocap_pos_noise: 0.001
    mocap_rot_noise: 0.001

/**/sim_param_server:
  ros__parameters:
    ground_truth_pub_rate: 0.01
    ground_truth_pos_noise: 0.001
    ground_truth_vel_noise: 0.005
    ground_truth_rot_noise: 0.001
    ground_truth_angular_noise: 0.005

    ground_truth_vel_drift: 0.1
    ground_truth_rot_drift: 0.1
    ground_truth_angular_drift: 0.01

    ground_truth_vel_drift_frequency: 1.0
    ground_truth_rot_drift_frequency: 1.0
    ground_truth_angular_drift_frequency: 0.01

    mocap_pub_rate: 0.01
    mocap_pos_noise: 0.001
    mocap_rot_noise: 0.001
