<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>aerial_robot_simulation</name>
  <version>0.0.0</version>
  <description>The simulation interface for aerial robot (ROS 2 / Humble port)</description>
  <maintainer email="johannes-kubel@dragon.t.u-tokyo.ac.jp">Johannes Kübel</maintainer>
  <license>BSD-3</license>
  <author email="j-sugihara@dragon.t.u-tokyo.ac.jp">Junichiro Sugihara</author>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>rosgraph_msgs</depend>
  <depend>aerial_robot_msgs</depend>
  <depend>spinal</depend>
  <depend>controller_manager_msgs</depend>
  <depend>controller_manager</depend>
  <depend>hardware_interface</depend>
  <depend>urdf</depend>
  <depend>urdfdom_headers</depend>
  <depend>ignition-math6</depend>
  <depend>ignition-gazebo6</depend>
  <depend>tinyxml2_vendor</depend>
  <depend>aerial_robot_model</depend>
  <depend>ros_gz_sim</depend>
  <depend>gz_ros2_control</depend>
  <depend>ros2_control</depend>
  <depend>ros2_controllers</depend>
  <depend>controller_interface</depend>
  <depend>ros_gz_bridge</depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend condition="$AERIAL_ROBOT_WITH_MUJOCO == 'true'">python3-mujoco</exec_depend>

  <!-- Linters -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_cmake_cppcheck</test_depend>
  <test_depend>ament_cmake_lint_cmake</test_depend>
  <test_depend>ament_cmake_pep257</test_depend>
  <test_depend>ament_cmake_xmllint</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
    <ignitionGazebo plugin_path="${prefix}/lib"/>
    <pluginlib plugin="${prefix}/aerial_robot_hw_sim_plugins.xml"/>

    <gazebo_ros gazebo_model_path="${prefix}/gazebo_model/model"/>
    <gazebo_ros gazebo_media_path="${prefix}/gazebo_model/world"/>
  </export>

</package>
